### ISSUE TITLE
Can't install Java on Pi Zero

### ISSUE THREAD

**Issue by samollari** [mphi-rc/pi-zero-security-key#2]
This isn't an issue with your repo, but how did you install Java on your Pi? I've been having problems with that

**Comment by samollari** [comment]
I managed to install it.
(I've been trying for a couple of days)

**Comment by mphi-rc** [comment]
It's surprisingly difficult! I don't believe Raspbian Buster supports Java on the Pi Zero.

The Pi Zero has an ARMv6 CPU which the OpenJDK JRE packages stopped supporting in Java 9. And Java 8 has reached end-of-life so was last available in Raspbian Stretch.

For anyone else having trouble: I've had success using the Zulu Community JRE from Azul as they still build and publish ARMv6 binaries. Go for [the 32-bit ARM hard-float version](https://www.azul.com/downloads/zulu-community/?architecture=arm-32-bit-hf&package=jdk).
